### ISSUE TITLE
Can't connect to elan

### ISSUE THREAD

**Issue by barnabasgoz** [zdar/elan2mqtt#2]
Hi!

I might be a little late for this repo, I don't know if it is active, but when I try to use the add-on, it drops this error:
`[2021-10-18 16:37:44,543] {socket_listener.py:296} ERROR - SOCKET LISTENER: Something went wrong. But don't worry we will start over again.
Traceback (most recent call last):
  File "/elan2mqtt-1.7.0/socket_listener.py", line 294, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/elan2mqtt-1.7.0/socket_listener.py", line 143, in main
    mqtt_cli.connect(mqtt_broker, 1883, 120)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)`

I use a raspberry pi 3b+ with the official Home assistant software installed directly, so I don't use Docker or anything like that.

**Comment by zdar** [comment]
Ok. The problem is not with eLan but with connection to your MQTT server. It is refused. 

"ConnectionRefusedError: [Errno 111] Connection refused"

Check config of MQTT (IP, username, password, opened ports on firewall if used). Try to use MQTT lens or other tool to test connection to your MQTT server first.

**Comment by zdar** [comment]
There is not an easy HowTo unfortunatelly.

Then you have to look at how the webinterface and API of elan works for your device. What messages and their format. Simply open elan in web browser and use developer console to look at the traffic.

Then you have to go trough HA documentation for MQTT devices (https://www.home-assistant.io/integrations/climate.mqtt/)
There you have to define correct templates for status and command payloads.

elan2mqtt does not do any processing. It only forwards payload between elan and HA.

This is quite tediuos problem. If you send me full log I can at least update elan2mqtt so that autodescovery works better. You can use it as starting point.
